version: '3.7'
services:
  mariadb:
    image: mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ecoswap
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_USER=ecoswap
      - MARIADB_PASSWORD=ecoswap
    volumes:
      - mysql_data:/var/lib/mysql
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      ecoswap:
        ipv4_address: 172.22.0.5
    ports:
      - 3306:3306

  php:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/symfony
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    links:
      - mariadb
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      ecoswap:
        ipv4_address: 172.22.0.4

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      ecoswap:
        ipv4_address: 172.22.0.3

volumes:
  mysql_data:

networks:
  ecoswap:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.2/16